/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Blog model module.
 * @module model/Blog
 * @version 1.0.0
 */
class Blog {
    /**
     * Constructs a new <code>Blog</code>.
     * @alias module:model/Blog
     * @param stext {String} 
     */
    constructor(stext) { 
        
        Blog.initialize(this, stext);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, stext) { 
        obj['stext'] = stext;
    }

    /**
     * Constructs a <code>Blog</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Blog} obj Optional instance to populate.
     * @return {module:model/Blog} The populated <code>Blog</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Blog();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('stext')) {
                obj['stext'] = ApiClient.convertToType(data['stext'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Blog.prototype['_id'] = undefined;

/**
 * @member {String} stext
 */
Blog.prototype['stext'] = undefined;






export default Blog;

